version: '3.8'
services:
    tf:
        image: datamgmtdemo01.eastasia.cloudapp.azure.com:30003/demo_project_01/demo-golden:27
        # command: sh -c "cp -r /app/* . && terraform init -backend-config="key=prod.${REPOSITORY}.tfstate" && terraform apply --auto-approve"
        command: sh -c "pwd && ls -l"
        volumes: 
            - .:/app
        working_dir: /app